services:
  - type: web
    name: rate-limiter-app
    env: docker
    plan: free
    healthCheckPath: /docs
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rate-limiter-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: rate-limiter-redis
          property: connectionString
      - key: ADMIN_TOKEN
        generateValue: true

  - type: redis
    name: rate-limiter-redis
    plan: free
    ipAllowList: []

databases:
  - name: rate-limiter-db
    databaseName: ratelimiter
    user: rl_user
    plan: free
